# Generated by Django 3.1 on 2020-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('technology', models.CharField(blank=True, default='', max_length=150)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to='project_image/%Y%m%d')),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to='project_image/%Y%m%d')),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to='project_image/%Y%m%d')),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('github_link', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, upload_to='CV')),
            ],
        ),
    ]
