# Generated by Django 3.1 on 2020-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='object'),
        ),
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
