# Generated by Django 3.1 on 2020-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200823_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='slug',
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='resume/'),
        ),
    ]
